### ISSUE TITLE
仙人掌连接自建 mqtt server, 发送语音后报错。

### ISSUE THREAD

**Issue by bluezd** [FoloToy/folotoy-server-self-hosting#139]
```
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,212 - DEBUG - STT type: openai-whisper
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,216 - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,225 - DEBUG - load_verify_locations cafile='/usr/local/lib/python3.11/site-packages/certifi/cacert.pem'
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,282 - DEBUG - Request options: {'method': 'post', 'url': '/audio/transcriptions', 'headers': {'Content-Type': 'multipart/form-data'}, 'files': [('file', SerializationIterator(index=0, iterator=<_io.BufferedReader name='/audio/recording-63d2f9f31b43468ab175078b7032b9be.wav'>))], 'json_data': {'model': 'whisper', 'language': 'zh', 'prompt': "ok. let's begin.", 'response_format': 'json'}}
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,302 - DEBUG - connect_tcp.started host='openai-jude.openai.azure.com' port=443 local_address=None timeout=5.0 socket_options=None
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,524 - DEBUG - connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f82b7b150>
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,524 - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x7f82b012e0> server_hostname='openai-jude.openai.azure.com' timeout=5.0
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,526 - DEBUG - start_tls.failed exception=ConnectError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1006)'))
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,527 - DEBUG - Encountered Exception
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
folotoy-server-self-hosting-folotoy-1  |     yield
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
folotoy-server-self-hosting-folotoy-1  |     resp = self._pool.handle_request(req)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
folotoy-server-self-hosting-folotoy-1  |     raise exc from None
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
folotoy-server-self-hosting-folotoy-1  |     response = connection.handle_request(
folotoy-server-self-hosting-folotoy-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
folotoy-server-self-hosting-folotoy-1  |     raise exc
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
folotoy-server-self-hosting-folotoy-1  |     stream = self._connect(request)
folotoy-server-self-hosting-folotoy-1  |              ^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 154, in _connect
folotoy-server-self-hosting-folotoy-1  |     stream = stream.start_tls(**kwargs)
folotoy-server-self-hosting-folotoy-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
folotoy-server-self-hosting-folotoy-1  |     with map_exceptions(exc_map):
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
folotoy-server-self-hosting-folotoy-1  |     self.gen.throw(typ, value, traceback)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
folotoy-server-self-hosting-folotoy-1  |     raise to_exc(exc) from exc
folotoy-server-self-hosting-folotoy-1  | httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1006)
folotoy-server-self-hosting-folotoy-1  |
folotoy-server-self-hosting-folotoy-1  | The above exception was the direct cause of the following exception:
folotoy-server-self-hosting-folotoy-1  |
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
folotoy-server-self-hosting-folotoy-1  |     response = self._client.send(
folotoy-server-self-hosting-folotoy-1  |                ^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
folotoy-server-self-hosting-folotoy-1  |     response = self._send_handling_auth(
folotoy-server-self-hosting-folotoy-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
folotoy-server-self-hosting-folotoy-1  |     response = self._send_handling_redirects(
folotoy-server-self-hosting-folotoy-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
folotoy-server-self-hosting-folotoy-1  |     response = self._send_single_request(request)
folotoy-server-self-hosting-folotoy-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
folotoy-server-self-hosting-folotoy-1  |     response = transport.handle_request(request)
folotoy-server-self-hosting-folotoy-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
folotoy-server-self-hosting-folotoy-1  |     with map_httpcore_exceptions():
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
folotoy-server-self-hosting-folotoy-1  |     self.gen.throw(typ, value, traceback)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
folotoy-server-self-hosting-folotoy-1  |     raise mapped_exc(message) from exc
folotoy-server-self-hosting-folotoy-1  | httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1006)
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,534 - DEBUG - 1 retry left
folotoy-server-self-hosting-folotoy-1  | 2024-03-26 20:07:38,535 - INFO - Retrying request to /audio/transcriptions in 0.755807 seconds
```

**Comment by lewangdev** [comment]
hi，请把docker-compose.yml和roles
.json 去掉 key 之后也发出来。

另外 azure 的 whisper 需要单独申请和部署的，可以现在azure网站上测试一下是否可以使用

**Comment by bluezd** [comment]
> hi，请把docker-compose.yml和roles .json 去掉 key 之后也发出来。

docker-compose.yml
```
version: '3'
volumes:
  emqx-etc:
  emqx-data:
  emqx-log:
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
      - "8083:8083/tcp"
    volumes:
      - emqx-etc:/opt/emqx/etc
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    environment:
      EMQX_NODE_NAME: emqx@node1.emqx.io
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./config:/config
    environment:
      TZ: Asia/Shanghai

      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /config/roles.json

      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt, dify-stt, aliyun-asr]
      STT_TYPE: openai-whisper

      # OpenAI Whisper
      OPENAI_WHISPER_API_BASE: https://openai-XXX.openai.azure.com
      OPENAI_WHISPER_KEY: XXX
      OPENAI_WHISPER_MODEL: whisper

      # Azure Whisper
      AZURE_WHISPER_API_BASE: https://openai-XXX.openai.azure.com
      AZURE_WHISPER_KEY: XXX
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Azure STT
      AZURE_STT_KEY: 3eba91b6143f4d3eeeeeeeeeeeeeeeeeeeeeeeee
      AZURE_STT_SERVICE_REGION: eastasia

      # Dify STT
      DIFY_STT_API_BASE: https://api.dify.ai/v1
      DIFY_STT_KEY: app-xxxxxxxxxxxxxxxxxxxxx

      # Aliyun ASR
      ALIYUN_ASR_ACCESS_KEY_ID: LTxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_ASR_ACCESS_KEY_SECRET: 3zWkHVxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_ASR_APP_KEY: Ltamxxxxxxxxxxxxxxxxxxxxx

      # Default LLM(Large Language Model) type
      # Options: [openai, azure-openai, gemini, dify, qianfan]
      LLM_TYPE: openai

      # OpenAI
      OPENAI_OPENAI_API_BASE: https://openai-XXX.openai.azure.com/
      OPENAI_OPENAI_MODEL: XXX
      OPENAI_OPENAI_KEY: XXX

      #Azure OpenAI
      AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
      AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
      AZURE_OPENAI_API_VERSION: "2023-05-15"
      #AZURE_OPENAI_MODEL: gpt-35-turbo

      #DIFY
      DIFY_API_BASE: https://api.dify.ai/v1
      DIFY_KEY: app-5YGbxxxxxxxxxxxxxxxxxxxxx

      #Xiaodu API
      XIAODU_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      XIAODU_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # GEMINI
      GEMINI_KEY: AIzaSyxxxxxxxxxxxxxxxxxxk

      # Qianfan
      QIANFAN_CLIENT_ID: 13rBTgxxxxxxxxxxxxxxxxxx
      QIANFAN_SECRET: zYxtMIQLexxxxxxxxxxxxxxxxxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [openai-tts, azure-tts, elevenlabs, edge-tts, aliyun-tts]
      # edge-tts is Free but slow
      TTS_TYPE: edge-tts

      # Azure TTS
      AZURE_TTS_KEY: 3eba91b6143f4d399edeeeeeeeeeeeeeeeeeeeee
      AZURE_TTS_SERVICE_REGION: eastasia

      # elevenlabs
      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      # OpenAI TTS
      OPENAI_TTS_KEY: sk-16XnP3HLHWho21oO2m0AAAAAAAAAAAAAAAAAAAAAA
      OPENAI_TTS_MODEL: tts-1

      # Aliyun TTS
      ALIYUN_TTS_ACCESS_KEY_ID: LTAI5t91NSxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_TTS_ACCESS_KEY_SECRET: 3zWkHVxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_TTS_APP_KEY: Ltamxxxxxxxxxxxxx

      AUDIO_DOWNLOAD_URL: http://192.168.99.100:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 192.168.99.100
      SPEECH_UDP_SERVER_PORT: 8085

      INTEGRATION_MQTT: true
``` 
roles.json
```
{
  "1": {
    "model": "gpt35turbo",
    "start_text": "你好，我是小兔兔，请问有什么我可以帮助你的吗？",
    "prompt": "你扮演一个孩子的小伙伴，名字叫小兔兔，性格和善，说话活泼可爱，对孩子充满爱心，经常赞赏和鼓励孩子，用5岁孩子容易理解语言提供有趣和创新的回答，每次回复根据聊天主题询问她的看法以激发她的思考和好奇心，现在她来到了你身边问了第一个问题:[你是谁]",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-XiaoxiaoNeural",
    "language": "zh"
  },
  "2": {
    "model": "gpt35turbo",
    "start_text": "你好，俺是东北兔，请问有什么俺可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“东北兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-liaoning-XiaobeiNeural",
    "language": "zh"
  },
  "3": {
    "model": "gpt35turbo",
    "start_text": "Hi, I'm Fofo. Nice to meet you.",
    "prompt": "Your name is \"Fofo\". Your task is to chat with me. Please respond in English, keeping your answers brief – no more than 50 words each time!",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "en-US-AnaNeural",
    "language": "en"
  },
  "4": {
    "model": "gpt35turbo",
    "start_text": "你好，额是陕西兔，请问有什么额可以帮助你的吗？ ",
    "prompt": "你擅于鼓励别人，乐观积极，无论别人和你说了什么，你都能夸对方，让人快乐",
    "max_message_count": 10,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-shaanxi-XiaoniNeural",
    "language": "zh"
  },
  "5": {
    "model": "gpt35turbo",
    "start_text": "你好，我是童话故事兔，想听什么童话故事吗？试试说，我想听听三只小猫咪的故事",
    "prompt": "你是一个知识渊博的智能机器人,你的名字叫“故事兔”，你的任务是讲故事给一位7岁孩子的听，你要先听取孩子想听的故事主题，然后根据孩子的说的内容，用中文讲一段故事，每个故事不超过200个字！",
    "max_message_count": 10,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-XiaoyiNeural",
    "language": "zh"
  },
  "6": {
    "model": "gpt35turbo",
    "start_text": "你好，我是台湾兔，请问有什么我可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“台湾兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 10,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-TW-HsiaoChenNeural",
    "language": "zh"
  },
  "7": {
    "model": "gpt35turbo",
    "start_text": "你好，我是口算兔，我们一起来玩玩口算游戏吧？",
    "prompt": "我是一个6岁小朋友，你陪我玩口算游戏。你出题，我回答结果。如果答对了你就说好棒，答错了你就告诉我正确答案，并且鼓励我。你一题一题的出，我一个个回答。不要有太多的解释说明。明白了吗？",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-YunxiaNeural",
    "language": "zh"
  }
}
```

> 另外 azure 的 whisper 需要单独申请和部署的，可以现在azure网站上测试一下是否可以使用
都已经单独部署了，本地通过 python 脚本测试是没有问题的。

@lewangdev
