### ISSUE TITLE
八爪鱼使用自建服务器，一直报timeout for 30 seconds

### ISSUE THREAD

**Issue by ForeverPx** [FoloToy/folotoy-server-self-hosting#163]
错误：
<img width="783" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/7984208/7634c1d6-8f76-4ffd-9e89-d5df192b2334">

docker日志：
```
folotoy-1  | 2024-05-22 14:58:33,530 - DEBUG - Received frame type: b'\x01'
folotoy-1  | 2024-05-22 14:59:48,188 - DEBUG - Received /user/folotoy/24d7eb738744/thing/event/post: message data: {'msgId': 3, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 1, 'changed': 1}}
folotoy-1  | 2024-05-22 14:59:49,062 - DEBUG - Speech synthesized with for ssml [<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" xml:lang="zh-CN"><voice name="zh-CN-YunyangNeural">你好，我是陪伴兔，请问有什么我可以帮助你的吗？</voice></speak>]
folotoy-1  | 2024-05-22 14:59:49,165 - DEBUG - Request tts_type=azure-tts time cost: 0.97s
folotoy-1  | 2024-05-22 14:59:49,168 - DEBUG - Publish topic: /user/folotoy/24d7eb738744/thing/command/call, msg: {"msgId": 3, "identifier": "updatestartvoice", "inputParams": {"url": "http://192.168.3.152:8082/voice-ab69087e1e6446c0b7267e978e11be1c.mp3", "keyCode": 1, "etag": "c8cdac08633f64f13b744afb46a8424c"}}
folotoy-1  | 2024-05-22 14:59:50,088 - DEBUG - Received /user/folotoy/24d7eb738744/thing/command/callAck: message data: {'msgId': 3, 'identifier': 'updatestartvoice', 'result': 1}
folotoy-1  | 2024-05-22 14:59:50,089 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24d7eb738744']}
nginx-1    | 192.168.65.1 - - [22/May/2024:06:59:52 +0000] "GET /voice-ab69087e1e6446c0b7267e978e11be1c.mp3 HTTP/1.1" 200 16704 "-" "-" "-"
nginx-1    | 192.168.65.1 - - [22/May/2024:07:00:02 +0000] "GET /voice-ab69087e1e6446c0b7267e978e11be1c.mp3 HTTP/1.1" 200 16704 "-" "ESP32HTTPClient" "-"
folotoy-1  | 2024-05-22 15:00:24,413 - DEBUG - Received /user/folotoy/24d7eb738744/thing/event/post: message data: {'msgId': 4, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 2, 'changed': 1}}
folotoy-1  | 2024-05-22 15:00:25,261 - DEBUG - Speech synthesized with for ssml [<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" xml:lang="zh-CN"><voice name="zh-CN-YunyangNeural">你好，俺是东北兔，请问有什么俺可以帮助你的吗？</voice></speak>]
folotoy-1  | 2024-05-22 15:00:25,440 - DEBUG - Request tts_type=azure-tts time cost: 1.03s
folotoy-1  | 2024-05-22 15:00:25,444 - DEBUG - Publish topic: /user/folotoy/24d7eb738744/thing/command/call, msg: {"msgId": 4, "identifier": "updatestartvoice", "inputParams": {"url": "http://192.168.3.152:8082/voice-764698d9623040479aa964ec7ecd1380.mp3", "keyCode": 2, "etag": "1d7c0368b903d28ffde8b8be6f241f07"}}
folotoy-1  | 2024-05-22 15:00:26,142 - DEBUG - Received /user/folotoy/24d7eb738744/thing/command/callAck: message data: {'msgId': 4, 'identifier': 'updatestartvoice', 'result': 1}
folotoy-1  | 2024-05-22 15:00:26,142 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24d7eb738744']}
nginx-1    | 192.168.65.1 - - [22/May/2024:07:00:26 +0000] "GET /voice-764698d9623040479aa964ec7ecd1380.mp3 HTTP/1.1" 200 17280 "-" "-" "-"
nginx-1    | 192.168.65.1 - - [22/May/2024:07:00:35 +0000] "GET /voice-764698d9623040479aa964ec7ecd1380.mp3 HTTP/1.1" 200 17280 "-" "ESP32HTTPClient" "-"
folotoy-1  | 2024-05-22 15:02:31,374 - DEBUG - Received /user/folotoy/24d7eb738744/thing/event/post: message data: {'msgId': 0, 'identifier': 'login', 'outParams': {'role': 2}}
folotoy-1  | 2024-05-22 15:02:31,379 - DEBUG - Publish topic: /user/folotoy/24d7eb738744/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": "9ccf1e98330c46a4ab64662121e846a6"}}
folotoy-1  | 2024-05-22 15:02:31,379 - DEBUG - Publish topic: /user/folotoy/24d7eb738744/thing/command/call, msg: {"msgId": 1, "identifier": "updateconfig", "inputParams": {"speechUdpServerHost": "192.168.3.152", "speechUdpServerPort": 8085}}
folotoy-1  | 2024-05-22 15:02:34,961 - DEBUG - Received /user/folotoy/24d7eb738744/thing/command/callAck: message data: {'msgId': 0, 'identifier': 'updatetoken', 'result': 1}
folotoy-1  | 2024-05-22 15:02:34,961 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24d7eb738744']}
folotoy-1  | 2024-05-22 15:02:35,331 - DEBUG - Received /user/folotoy/24d7eb738744/thing/data/post: message data: {'msgId': 1, 'identifier': 'data_config', 'outParams': {'hardware_ver': '0.8.1.3', 'software_version': '24.17.4.30', 'devicekey': '24d7eb738744', 'voice_threshold': 55, 'record_type': 2, 'timeout': 30, 'open_tip_type': 1, 'volume': 100, 'role': 2, 'led_brightness': 255}}
folotoy-1  | 2024-05-22 15:02:35,381 - DEBUG - Received /user/folotoy/24d7eb738744/thing/command/callAck: message data: {'msgId': 1, 'identifier': 'updateconfig', 'result': 1}
folotoy-1  | 2024-05-22 15:02:35,382 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24d7eb738744']}
folotoy-1  | 2024-05-22 15:02:35,382 - DEBUG - Received /user/folotoy/24d7eb738744/thing/event/post: message data: {'msgId': 2, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 2, 'changed': 1}}
folotoy-1  | 2024-05-22 15:02:35,383 - DEBUG - Publish topic: /user/folotoy/24d7eb738744/thing/command/call, msg: {"msgId": 2, "identifier": "updatestartvoice", "inputParams": {"url": "http://192.168.3.152:8082/voice-764698d9623040479aa964ec7ecd1380.mp3", "keyCode": 2, "etag": "1d7c0368b903d28ffde8b8be6f241f07"}}
folotoy-1  | 2024-05-22 15:02:36,044 - DEBUG - Received /user/folotoy/24d7eb738744/thing/command/callAck: message data: {'msgId': 2, 'identifier': 'updatestartvoice', 'result': 1}
folotoy-1  | 2024-05-22 15:02:36,044 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24d7eb738744']}
folotoy-1  | 2024-05-22 15:02:46,468 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 20B
folotoy-1  | 2024-05-22 15:02:46,469 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 1
folotoy-1  | 2024-05-22 15:02:46,469 - DEBUG - Received frame type: b'\x02'
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 1043B
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 1
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Received frame type: b'\x01'
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 1043B
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 1
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Received frame type: b'\x01'
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 1043B
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 1
folotoy-1  | 2024-05-22 15:02:47,528 - DEBUG - Received frame type: b'\x01'
folotoy-1  | 2024-05-22 15:02:47,667 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 1043B
folotoy-1  | 2024-05-22 15:02:47,668 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 1
folotoy-1  | 2024-05-22 15:02:47,668 - DEBUG - Received frame type: b'\x01'
folotoy-1  | 2024-05-22 15:02:47,727 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 1043B
folotoy-1  | 2024-05-22 15:02:47,727 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 1
folotoy-1  | 2024-05-22 15:02:47,727 - DEBUG - Received frame type: b'\x01'
folotoy-1  | 2024-05-22 15:02:47,727 - DEBUG - Peer: ('192.168.65.1', 44982) Len: 1043B
…………………………………………………………
folotoy-1  | 2024-05-22 15:03:39,925 - DEBUG - Received token: 9ccf1e98330c46a4ab64662121e846a6 RecordingId: 2
folotoy-1  | 2024-05-22 15:03:39,925 - DEBUG - Received frame type: b'\x01'


```

docker-compose.yml
```
version: '3'
volumes:
  emqx-etc:
  emqx-data:
  emqx-log:
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
      - "8083:8083/tcp"
    volumes:
      - emqx-etc:/opt/emqx/etc    
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    environment:
      EMQX_NODE_NAME: emqx@node1.emqx.io
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./config:/config
    environment:
      TZ: Asia/Shanghai

      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /config/roles.json

      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt, dify-stt, aliyun-asr]
      STT_TYPE: azure-stt

      # OpenAI Whisper
      #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.com/v1
      OPENAI_WHISPER_KEY: sk-Gnkw1Znxxxxxxxxxxxddddddddddddddd
      OPENAI_WHISPER_MODEL: whisper-1
      
      # Azure Whisper
      AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
      AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Azure STT
      AZURE_STT_KEY: f1c203dc8xxxxxxxxxx34ed7a62552
      AZURE_STT_SERVICE_REGION: eastasia

      # Dify STT
      DIFY_STT_API_BASE: https://api.dify.ai/v1
      DIFY_STT_KEY: app-xxxxxxxxxxxxxxxxxxxxx
      
      # Aliyun ASR
      ALIYUN_ASR_ACCESS_KEY_ID: LTxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_ASR_ACCESS_KEY_SECRET: 3zWkHVxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_ASR_APP_KEY: Ltamxxxxxxxxxxxxxxxxxxxxx

      # Default LLM(Large Language Model) type
      # Options: ['openai', 'azure-openai', 'gemini', 'dify', 'qianfan', 'xiaodu',
      #           'ollama', 'groq', 'moonshot', 'anthropic', 'zhipu', 'lingyiwanwu', 
      #           'dashscope', 'spark-desk', 'minimax', 'aws-bedrock']
      LLM_TYPE: moonshot

      # OpenAI
      #OPENAI_OPENAI_API_BASE: https://one-api.xxx.com/v1
      #OPENAI_OPENAI_MODEL: gpt-3.5-turbo
      OPENAI_OPENAI_KEY: sk-5N8F5VXsa7oOZI8Q874601110AAAAAAAAAAAAAAAAAAAAAA

      #Azure OpenAI
      AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
      AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
      AZURE_OPENAI_API_VERSION: "2023-05-15"
      #AZURE_OPENAI_MODEL: gpt-35-turbo

      #DIFY
      DIFY_API_BASE: https://api.dify.ai/v1
      DIFY_KEY: app-5YGbxxxxxxxxxxxxxxxxxxxxx
      
      #Xiaodu API
      XIAODU_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      XIAODU_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # GEMINI
      GEMINI_KEY: AIzaSyxxxxxxxxxxxxxxxxxxk
      
      # Qianfan
      QIANFAN_CLIENT_ID: 13rBTgxxxxxxxxxxxxxxxxxx
      QIANFAN_SECRET: zYxtMIQLexxxxxxxxxxxxxxxxxx

      # Moonshot
      MOONSHOT_API_BASE: https://api.moonshot.cn/v1
      MOONSHOT_KEY: sk-q5IaDxxxxxxxxxxxxxxxu6mFHYxCSJ1EppGV
      MOONSHOT_MODEL: moonshot-v1-8k

      # Aliyun Dashscope
      DASHSCOPE_KEY: sk-f4x
      DASHSCOPE_MODEL: qwen-turbo
      DASHSCOPE_ENABLE_SEARCH: true
      
      # Lingyiwanwu
      LINGYIWANWU_KEY: 4b2f584b4x
      LINGYIWANWU_MODEL: yi-34b-chat-200k
      
      # Zhipu
      ZHIPU_KEY: 4544625bb0d0ax
      #ZHIPU_MODEL=glm-3-turbo
      
      # Spark Desk
      SPARK_DESK_API_VERSION: v2.0
      SPARK_DESK_APP_ID: d2c1xxxxxxxxxxx
      SPARK_DESK_API_KEY: 10610b3xxxxxxx
      SPARK_DESK_API_SECRET: N2I5xxxxxxxxx
      SPARK_DESK_TEMPERATURE: 0.7
      SPARK_DESK_MAX_TOKENS: 4096
      
      # MINIMAX
      MINIMAX_KEY: eyJhbGciOiJSUzI1NiIsInRxxxxxxxxxxxxxxx

      # AWS Bedrock
      AWS_BEDROCK_ACCESS_KEY_ID: AKIAQLJIxxxxxxxxxxxxxxxxxxx
      AWS_BEDROCK_ACCESS_KEY_SECRET: ss07ojxxW/X7YHZkxxxxxxxxxx
      AWS_BEDROCK_MODEL: anthropic.claude-v2:1
      
      # FastGPT
      FASTGPT_KEY: here-is-app-key-not-account-key
      #FASTGPT_API_BASE: https://api.fastgpt.in/api
      #FASTGPT_CHAT_ID: xxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [openai-tts, azure-openai-tts, azure-tts, dify-tts, elevenlabs, edge-tts, aliyun-tts]
      # edge-tts is Free but slow
      TTS_TYPE: azure-tts

      # Azure TTS
      AZURE_TTS_KEY: f1c20xxxxxxxxxxxxed7a62552
      AZURE_TTS_SERVICE_REGION: eastasia

      # elevenlabs
      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      # OpenAI TTS
      OPENAI_TTS_KEY: sk-16XnP3HLHWho21oO2m0AAAAAAAAAAAAAAAAAAAAAA
      OPENAI_TTS_MODEL: tts-1  

      # Aliyun TTS
      ALIYUN_TTS_ACCESS_KEY_ID: LTAI5t91NSxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_TTS_ACCESS_KEY_SECRET: 3zWkHVxxxxxxxxxxxxxxxxxxxxx
      ALIYUN_TTS_APP_KEY: Ltamxxxxxxxxxxxxx

      # Azure Openai TTS
      AZURE_OPENAI_TTS_API_BASE: https://xxx-whisper.openai.azure.com/
      AZURE_OPENAI_TTS_API_VERSION: 2024-02-15-preview
      AZURE_OPENAI_TTS_DEPLOYMENT_NAME: tts
      AZURE_OPENAI_TTS_KEY: 01fdbc75bdxxxxxx
      AZURE_OPENAI_TTS_MODEL: tts-1

      # Dify TTS
      DIFY_TTS_API_BASE: https://api.dify.ai/v1
      DIFY_TTS_KEY: app-5YGbAx
      
      AUDIO_DOWNLOAD_URL: http://192.168.3.152:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 192.168.3.152
      SPEECH_UDP_SERVER_PORT: 8085

```

roles.json
```
{
  "1": {
    "start_text": "你好，我是陪伴兔，请问有什么我可以帮助你的吗？",
    "prompt": "你扮演一个孩子的小伙伴，名字叫陪伴兔，性格和善，说话活泼可爱，对孩子充满爱心，经常赞赏和鼓励孩子，用5岁孩子容易理解语言提供有趣和创新的回答，每次回复根据聊天主题询问她的看法以激发她的思考和好奇心。",
    "max_message_count": 5
  },
  "2": {
    "start_text": "你好，俺是东北兔，请问有什么俺可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“东北兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 5
  },
  "3": {
    "start_text": "Hi, I'm Fofo. Nice to meet you.",
    "prompt": "You're a knowledgeable and helpful AI named \"Fofo\". Your task is to chat with me. Please respond in English, keeping your answers brief – no more than 50 words each time!",
    "max_message_count": 5
  },
  "4": {
    "start_text": "你好，额是夸夸兔，请问有什么额可以帮助你的吗？ ",
    "prompt": "夸夸我",
    "max_message_count": 5
  },
  "5": {
    "start_text": "你好，我是口算兔，我们一起来玩玩口算游戏吧？",
    "prompt": "我是一个6岁小朋友，你陪我玩口算游戏。你出题，我回答结果。如果答对了你就说好棒，答错了你就告诉我正确答案，并且鼓励我。你一题一题的出，我一个个回答。不要有太多的解释说明。明白了吗？",
    "max_message_count": 5
  },
  "6": {
    "start_text": "你好，我是台湾兔，请问有什么我可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“台湾兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 5
  },
  "7": {
    "start_text": "你好，我是小兔，请问有什么我可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“小兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 5
  }
}
```
