### ISSUE TITLE
说话后没有反应

### ISSUE THREAD

**Issue by fyunpeng** [FoloToy/folotoy-server-self-hosting#18]
```yml
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: INFO

      ROLES_FILE_PATH: /roles.json

      #OPENAI_API_BASE: https://xxx.com/v1
      OPENAI_OPENAI_KEY: sk-3ypHOzsaNObFiykz3FnjT3BlbkFJo6xxxQ9Gc2d0JkR3wo

      #OPENAI_OPENAI_TYPE: azure
      AZURE_OPENAI_KEY: xxx
      AZURE_OPENAI_ENDPOINT: https://openaigpt4chat.openai.azure.com/
      AZURE_OPENAI_VERSION: 2023-07-01-preview

      AZURE_TTS_KEY: 6ebbf8b8bf1b412ead8xxx
      AZURE_TTS_SERVICE_REGION: eastus

      AUDIO_DOWNLOAD_URL: http://20.197.240.221:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy_server
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 20.197.240.221
      SPEECH_UDP_SERVER_PORT: 8085

      #Baidu Wenyanyixin API
      #LLM_TYPE: wenyanyixin
      #WENYANYIXIN_CLIENT_ID:
      #WENYANYIXIN_SECRET:

```
