### ISSUE TITLE
使用asure的openai，硬件没有问题，可连服务器，对话没有反馈

### ISSUE THREAD

**Issue by qushitu** [FoloToy/folotoy-server-self-hosting#19]
硬件没有问题，用您那边的服务器测试过，用我部署的服务器，可以连接上，但是对话没有反馈；
配置如下，请问是出了什么问题
root@HHT:/opt/folotoy-server-self-hosting# cat docker-compose.yml 
```yml
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: INFO

      ROLES_FILE_PATH: /roles.json

      #OPENAI_API_BASE: https://xxx.com/v1
      OPENAI_OPENAI_KEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

      OPENAI_OPENAI_TYPE: azure
      AZURE_OPENAI_KEY: e3ea5e95d2024********9a017084564ff
      AZURE_OPENAI_ENDPOINT: https://fohuohuotugpt.openai.azure.com/
      AZURE_OPENAI_VERSION: "2022-12-01"

      AZURE_TTS_KEY: 06e205e247******65c3706f721
      AZURE_TTS_SERVICE_REGION: eastus

      AUDIO_DOWNLOAD_URL: http://64.**.**.27:8082 （隐藏局部）
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy_server
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 64.**.**.27（隐藏局部）
      SPEECH_UDP_SERVER_PORT: 8085

      #Baidu Wenyanyixin API
      #LLM_TYPE: wenyanyixin
      #WENYANYIXIN_CLIENT_ID:
      #WENYANYIXIN_SECRET:
```
