### ISSUE TITLE
mitu c1: timeout for 30 seconds

### ISSUE THREAD

**Issue by ttys3** [FoloToy/folotoy-server-self-hosting#228]
no "Received frame type xxx" log on server side

after record button released, no response sound play.


client side tty:

```
I: StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
I: StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
I: StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
I: record end button pressed
                                                                                                                                                                                                                       FSM=====================record_exit======
============================
FSM=====================atob========================================
FSM=====================wait_enter==================================
I: local audiI: [EVENT] ROBOT_THINK
                                   o url:/audio/default/record-over.mp3
                                                                       I: local audio change:0
                                                                                              Timeout for 30 seconds!
FSM=====================wait_exit==================================
FSM=====================atob========================================
FSM=====================idle_enter==================================
I: [EVENT] ROBOT_IDLE
```

server log:

![image](https://github.com/user-attachments/assets/6c3cae58-d864-4439-af2f-6369a4908b27)


related env config:

```toml
[env]
# https://docs.folotoy.com/docs/configuration/environment_variables/
  API_SERVER = "true"
  API_SERVER_BIND_ADDRESS = "0.0.0.0"
  API_SERVER_PORT = "8082"
  AUDIO_DOWNLOAD_URL = "xxxxxxxxxxxxx"
  AUDIO_SAVE_PATH = "/audio"
  LOG_LEVEL = "DEBUG"
  MQTT_BROKER_HOST = "127.0.0.1"
  MQTT_BROKER_PORT = "1883"
  MQTT_CLIENT_ID = "folotoy"
  MQTT_USERNAME = "folotoy"
  LLM_TYPE = "openai"

  OPENAI_OPENAI_API_BASE = "https://openrouter.ai/api/v1"
  OPENAI_OPENAI_MODEL = "deepseek/deepseek-chat"

  ROLES_FILE_PATH = "/config/roles.json"
  SPEECH_UDP_SERVER_BIND_ADDRESS = "0.0.0.0"
SPEECH_UDP_SERVER_HOST = "xxxxxxxxxxxxx"
  SPEECH_UDP_SERVER_PORT = "8085"
  STT_TYPE = "azure-stt"
  TTS_TYPE = "edge-tts"
```
