### ISSUE TITLE
八爪鱼联接coze后不能实现上下文对话

### ISSUE THREAD

**Issue by congcong009** [FoloToy/folotoy-server-self-hosting#234]
我的配置如下：
```json
{
  "wifi": {
    "enable": true,
    "ssid": "****",
    "password": "****",
    "config_type": 1
  },
  "common": {
    "hardware_ver": "0.8.1.3",
    "software_ver": "25.6.4.49",
    "lamp_ver": "1.1",
    "log_level": 5,
    "productkey": "folotoy",
    "devicekey": "****",
    "firstboot": false,
    "role": 1,
    "old_role": 1,
    "etag": {
      "1": "eb19da****",
      "2": "",
      "3": "",
      "4": "",
      "5": "",
      "6": "",
      "7": ""
    },
    "voice_start_threshold": 60,
    "voice_end_threshold": 55,
    "record_type": 1,
    "timeout": 30,
    "open_tip_type": 1,
    "voltage_alarm": 3.7,
    "sleep_trigger_time": 0,
    "sleep_when_charging": false,
    "led_brightness": 255,
    "volume": 100,
    "volume_control_type": 1,
    "io_output": false,
    "record_begin_audio_type": 0,
    "send_battery_msg_time": 300,
    "no_sound_duration": 2000,
    "wake_up_mode": 1,
    "io_control_conversation_mode": false,
    "standby_mode": false,
    "standby_time": 600,
    "asr_mode": false,
    "temp_threshold": 68,
    "motor_mode": 0,
    "motor_start_duration_ms": 600,
    "motor_stop_duration_ms": 100,
    "accel_click_threshold": 20,
    "pair_token": ""
  },
  "mqtt": {
    "enable": true,
    "broker": "182.43.**.**",
    "port": 1883,
    "cid": "ec64****",
    "username": "ec64****",
    "password": "****"
  },
  "udpSpeechServer": {
    "address": "182.43.**.**",
    "port": 8085
  }
}
OK
```
role.json里的"max_message_count"也配置为10了，但在和agent通信后，不能记录上下文，coze后台显示如下，可以看到，会话ID每次都是新建，这导致模型不断在重复身份识别等第一个步骤，无法继续上下文对话

![Image](https://github.com/user-attachments/assets/7c677ca5-4f31-4b94-b1fd-358960f069b5)

请问是我哪里配置不对吗？谢谢

**Comment by lewangdev** [comment]
在 roles.json 中添加 conversation_id 或者 docker-compose.yml 添加 COZE_CONVERSATION_ID

**Comment by congcong009** [comment]
```yaml
      # LLM Service
      LLM_TYPE: coze
      COZE_PERSONAL_ACCESS_TOKEN: pat_OXqdD***
      COZE_BOT_ID: 747926953***
      COZE_API_BASE: https://api.coze.cn/v3
      COZE_TIMEOUT: 15
      COZE_CONVERSATION_ID: 748341217***
```
不行，重编译容器并重启设备，不能记录这个对话

如果换官方的服务器并进行接口授权，对话就ok了

![Image](https://github.com/user-attachments/assets/8af82c2e-9e34-4f6f-bde2-6f55100333f9)

请问这是需要等八爪鱼的新版本rom吗？
