### ISSUE TITLE
没有声音，一直绿灯

### ISSUE THREAD

**Issue by jingdizhilh** [FoloToy/folotoy-server-self-hosting#24]
```yml
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: INFO

      ROLES_FILE_PATH: /roles.json

      #OPENAI_API_BASE: https://xxx.com/v1
      OPENAI_OPENAI_KEY: sk-7C8FQOzCunJlH2TdCPZST3BlbkFJqFh*******

      #OPENAI_OPENAI_TYPE: azure
      AZURE_OPENAI_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxx

      AZURE_OPENAI_ENDPOINT: https://chatgpt.link/v1
      AZURE_OPENAI_VERSION: 2023-07-01-preview

      AZURE_TTS_KEY: 9a0cd7c0b8dc4bd09458**********
      AZURE_TTS_SERVICE_REGION: eastus2

      AUDIO_DOWNLOAD_URL: http://20.81.***.**:8082
      AUDIO_SAVE_PATH: /audio

# MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy_server
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 20.81.***.**
      SPEECH_UDP_SERVER_PORT: 8085

      #Baidu Wenyanyixin API
      #LLM_TYPE: wenyanyixin
      #WENYANYIXIN_CLIENT_ID:
      #WENYANYIXIN_SECRET:
```
日志 ：

```txt
folotoy-server-self-hosting-nginx-1    | 4.151.168.167 - - [06/Oct/2023:01:59:46 +0000] "GET /z/ HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/06 01:59:46 [error] 28#28: *546 "/usr/share/nginx/html/acceso/index.html" is not found (2: No such file or directory), client: 4.151.168.167, server: localhost, request: "GET /acceso/ HTTP/1.1", host: "20.81.***.**:8082"
folotoy-server-self-hosting-nginx-1    | 4.151.168.167 - - [06/Oct/2023:01:59:46 +0000] "GET /acceso/ HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/06 01:59:46 [error] 28#28: *547 "/usr/share/nginx/html/access/index.html" is not found (2: No such file or directory), client: 4.151.168.167, server: localhost, request: "GET /access/ HTTP/1.1", host: "20.81.**:8082"
folotoy-server-self-hosting-nginx-1    | 4.151.168.167 - - [06/Oct/2023:01:59:46 +0000] "GET /access/ HTTP/1.1" 404 153 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:04:58:12 +0000] "GET /voice-c5f70f5408fc4d6aab57263effe2a267.mp3 HTTP/1.1" 200 23760 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 77.90.185.169 - - [06/Oct/2023:05:04:49 +0000] "\x16\x03\x01\x01T\x01\x00\x01P\x03\x03e\xE4\xD8\x9Cw\xD2\xBD\x03\x10PO\xDBy\xE7\x14\xE5\x88\x93p\x22\xC2\x22\xFEY-\xA3\xE1\xE0\x94\x8D\xAE\x85 \xB10\xA1\x10-\x85\x81\xAD\x86\xADl)O&\x9B\xD2\x11N\xD59\xB5\xFA\xF3\xA1\xDA{t\xE5r\x1B\x99\x88\x00v\x13\x02\x13\x03\x13\x01\xC0/\xC0+\xC00\xC0,\x00\x9E\xC0'\x00g\xC0(\x00k\x00\xA3\x00\x9F\xCC\xA9\xCC\xA8\xCC\xAA\xC0\xAF\xC0\xAD\xC0\xA3\xC0\x9F\xC0]\xC0a\xC0W\xC0S\x00\xA2\xC0\xAE\xC0\xAC\xC0\xA2\xC0\x9E\xC0\x5C\xC0`\xC0V\xC0R\xC0$\x00j\xC0#\x00@\xC0" 400 157 "-" "-" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:05:44:22 +0000] "GET /voice-1b110df61d2f489084913840a942e75c.mp3 HTTP/1.1" 200 20592 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 45.79.181.223 - - [06/Oct/2023:05:52:13 +0000] "\x16\x03\x01\x00\x85\x01\x00\x00\x81\x03\x03\x01\xE5\xCD\x08'\xDA8s(s\xA0\xAAge" 400 157 "-" "-" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:06:11:27 +0000] "GET /voice-6a9ccb38ec704edd91217b38282a0448.mp3 HTTP/1.1" 200 20592 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:06:11:33 +0000] "GET /voice-7d9a0c13ad7d4b3fa438a4b60ab801a5.mp3 HTTP/1.1" 200 17424 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:06:12:32 +0000] "GET /voice-770a9959d7cc4c98a9177cee9510bd52.mp3 HTTP/1.1" 200 23760 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:06:12:51 +0000] "GET /voice-c65fadd803514c2ea68b0ecdf05baa93.mp3 HTTP/1.1" 200 21024 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:06:13:25 +0000] "GET /voice-7d9a0c13ad7d4b3fa438a4b60ab801a5.mp3 HTTP/1.1" 200 17424 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:06:45:02 +0000] "GET /voice-be91b26b2e9c4460a13cfaace90b3208.mp3 HTTP/1.1" 200 20592 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:54 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:54 [notice] 28#28: gracefully shutting down
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:54 [notice] 28#28: exiting
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:54 [notice] 28#28: exit
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:55 [notice] 1#1: signal 17 (SIGCHLD) received from 28
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:55 [notice] 1#1: worker process 28 exited with code 0
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:36:55 [notice] 1#1: exit
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
folotoy-server-self-hosting-nginx-1    | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Configuration complete; ready for start up
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: using the "epoll" event method
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: nginx/1.25.2
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14)
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: OS: Linux 5.15.0-1049-azure
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: start worker processes
folotoy-server-self-hosting-nginx-1    | 2023/10/06 07:37:59 [notice] 1#1: start worker process 22
folotoy-server-self-hosting-folotoy-1  | 2023-10-06 07:47:53,694 - ThreadPoolExecutor-0_0 - thread.py(58) - INFO - Dkey a0a3b3189720: Transcript is empty
folotoy-server-self-hosting-folotoy-1  | 2023-10-06 07:48:03,905 - ThreadPoolExecutor-0_1 - thread.py(58) - INFO - Dkey a0a3b3189720: Transcribed:字幕視聴ありがとうございました。
folotoy-server-self-hosting-folotoy-1  | 2023-10-06 07:48:13,061 - ThreadPoolExecutor-0_0 - thread.py(58) - INFO - Dkey a0a3b3189720: Transcribed:ご視聴ありがとうございました。
folotoy-server-self-hosting-nginx-1    | 175.0.50.252 - - [06/Oct/2023:07:48:25 +0000] "GET /voice-7c4a41a8a8754e5eb7e884c4e45984c6.mp3 HTTP/1.1" 200 17424 "-" "ESP32HTTPClient" "-"
folotoy-server-self-hosting-folotoy-1  | 2023-10-06 07:48:28,622 - ThreadPoolExecutor-0_1 - thread.py(58) - WARNING - Dkey a0a3b3189720: Audio file is too short. Minimum audio length is 0.1 seconds. Now is 0.048 seconds
^Ccanceled

```
