### ISSUE TITLE
无法访问18083管理后台

### ISSUE THREAD

**Issue by qhhsy** [FoloToy/folotoy-server-self-hosting#35]
//docker-compose.yml

``` yml
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /roles.json

      STT_TYPE: openai-whisper
      #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.com/v1
      OPENAI_WHISPER_MODEL: whisper-1
      OPENAI_WHISPER_KEY: sk-balabala

      #STT_TYPE: azure-whisper
      AZURE_WHISPER_API_BASE: https://xxxx-whisper.openai.azure.com
      AZURE_WHISPER_KEY: 9afbef65bcf648768aaaaaaaaaaaaaaaaaaa
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      LLM_TYPE: openai
      # Please do not use OPENAI_API_BASE here
      #OPENAI_OPENAI_API_BASE: https://one-api.xxxx.com/v1
      OPENAI_OPENAI_KEY: sk-balabala

      #Azure OpenAI
      #LLM_TYPE: azure-openai    
      AZURE_OPENAI_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      AZURE_OPENAI_ENDPOINT: https://folotoy2.openai.azure.com/
      AZURE_OPENAI_VERSION: "2023-05-15"

      #Baidu YIYAN API
      #LLM_TYPE: yiyan
      YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Free but slow
      #TTS_TYPE: edge-tts

      TTS_TYPE: azure-tts
      AZURE_TTS_KEY: balabala
      AZURE_TTS_SERVICE_REGION: japaneast

      #TTS_TYPE: elevenlabs
      ELEVENLABS_TTS_KEY: aaaaaaaaaaaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      AUDIO_DOWNLOAD_URL: http://balabala:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy_server
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: balabala
      SPEECH_UDP_SERVER_PORT: 8085
```

// logs

```
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:35,672 - MainThread - main.py(6) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:38,776 - MainThread - main.py(6) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:38,777 - MainThread - main.py(6) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-emqx-1 exited with code 0
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:40,779 - MainThread - main.py(6) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:40,780 - MainThread - main.py(6) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-emqx-1     | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1     | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1     | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:42,781 - MainThread - main.py(6) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-20 09:22:42,782 - MainThread - main.py(6) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-emqx-1     | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
```
