### ISSUE TITLE
access token 转 api key 实现免 api key 使用 folotoy 玩具

### ISSUE THREAD

**Issue by william5200** [FoloToy/folotoy-server-self-hosting#49]
首先感谢 linweiyuan 大佬的开源项目 go-chatgpt-api :  
https://github.com/linweiyuan/go-chatgpt-api

两种方法  

方法1：vps 安装 go-chatgpt-api 直接中转，无需 one-api  
方法2：利用 go-chatgpt-api 把 access token 转为 api ，再利用 one-api 中转和管理 api  

经测试，两种方法速度差异不大，速度主要取决于网络状况。  

### 第一步  
这里分 A/B 两种情况：
#### A: vps 能够直连 openai  
compose.yml 配置如下:  
```
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
```
#### B. vps 无法直连 openai , 或使用上述 A 配置无法成功启动项目，或其他异常问题，可以尝试使用 warp 访问 openai  
compose.yml 配置如下：  
```
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
```
保存配置文件，运行:  
`docker compose up -d`  

查看 logs: 
`docker logs -f go-chatgpt-api`  

显示如下表示启动成功：  
```
INFO[0000] service go-chatgpt-api is ready   
```
### 第二步  

修改 folotoy 配置文件 docker-compose.yml 中 OPENAI 字段：
```
OPENAI_OPENAI_API_BASE: http://ip:8080/platform/v1  # ip 改为当前 vps 的实际 ip , 注意后面需要添加 /platform/v1 字段
OPENAI_OPENAI_KEY: xxx  # xxx处填写 openai 的 access token
```
OPENAI ACCESS TOKEN 获取：
登录 OPENAI 账号后点击如下地址，复制 accessToken 字段，如 `eyJhbGciOiJSUzI1NiIsInR5cCI.........`  
https://chat.openai.com/api/auth/session

重启 folotoy ： `docker compose up -d`  

完成配置即可使用。

### 第一步  

参考前文建立 go-chatgpt-api 的 配置文件 compose.yml 并运行  

### 第二步  

第一步成功运行后，进入 one-api 后台->渠道->创建新的渠道->提交，参考配置如下：  

![image](https://github.com/william5200/ProgramNotes/assets/33442913/42c9b163-a4e6-4745-b90e-28a4de36e056)

密钥：填写上述 access token  

代理：填写 http://ip:8080/platform  

这样就可以把这个渠道作为一个 api 渠道来使用了。

**注意：**  使用本方法时， folotoy 配置文件 docker-compose.yml 中 OPENAI_OPENAI_API_BASE 字段后面记得添加 v1，参考配置如下：  
```
OPENAI_OPENAI_API_BASE: http://ip:3000/v1  # ip 改为当前 vps 的 ip 地址
OPENAI_OPENAI_KEY: sk-xxx  # 此处填写 one-api 的 api key
```

添加成功后测试，两个渠道的响应时间不相上下：  

![image](https://github.com/william5200/ProgramNotes/assets/33442913/4dd0a75c-e92e-4412-8e28-7cacd4104a4e)

最后，可以禁用原有的 api key 渠道，以便节省 api 用量。

Enjoy!
