### ISSUE TITLE
服务器能有录音文件，但是红灯闪烁后无响应

### ISSUE THREAD

**Issue by faye25tom** [FoloToy/folotoy-server-self-hosting#64]
日志：

```text
2023-11-11 13:41:08,655 - MainThread - main.py(6) - DEBUG - Peer: ('119.123.34.128', 20032) Len: 20B
2023-11-11 13:41:08,655 - MainThread - main.py(6) - DEBUG - Received token: 6b50fcade56c43af8db510abec239d38 RecordingId: 7
2023-11-11 13:41:08,655 - MainThread - main.py(6) - DEBUG - Received frame type: b'\x02'
2023-11-11 13:41:08,656 - ThreadPoolExecutor-0_0 - thread.py(58) - DEBUG - Current dkey=a0a3b30fb640 role=6
2023-11-11 13:41:08,657 - ThreadPoolExecutor-0_0 - thread.py(58) - DEBUG - STT type: azure-stt
2023-11-11 13:41:08,658 - ThreadPoolExecutor-0_0 - thread.py(58) - ERROR - Record error: Traceback (most recent call last):
  File "core/speech_server.py", line 196, in core.speech_server.SpeechServer.write_wav
  File "sdk/stt.py", line 27, in sdk.stt.SttSdk.transcribe
  File "sdk/stt.py", line 49, in sdk.stt.SttSdk.azure_stt
  File "sdk/stt_sdk/azure_stt.py", line 19, in sdk.stt_sdk.azure_stt.AzureSttEngine.sound_to_text
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/speech.py", line 84, in __init__
    raise ValueError(generic_error_message)
ValueError: cannot construct SpeechConfig with the given arguments
Traceback (most recent call last):
  File "core/speech_server.py", line 196, in core.speech_server.SpeechServer.write_wav
  File "sdk/stt.py", line 27, in sdk.stt.SttSdk.transcribe
  File "sdk/stt.py", line 49, in sdk.stt.SttSdk.azure_stt
  File "sdk/stt_sdk/azure_stt.py", line 19, in sdk.stt_sdk.azure_stt.AzureSttEngine.sound_to_text
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/speech.py", line 84, in __init__
    raise ValueError(generic_error_message)
ValueError: cannot construct SpeechConfig with the given arguments
```

配置如下：

roles.json
```json
{
  "1": {
    "model": "gpt-3.5-turbo",
    "start_text": "你好，我是小兔兔，请问有什么我可以帮助你的吗？",
    "prompt": "你扮演一个孩子的小伙伴，名字叫小兔兔，性格和善，说话活泼可爱，对孩子充满爱心，经常赞赏和鼓励孩子，用5岁孩子容易理解语言提供有趣和创新的回答，每次回复根据聊天主题询问她的看法以激发她的思考和好奇心，现在她来到了你身边问了第一个问题:[你是谁]",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-XiaoxiaoNeural",
    "language": "zh-CN",
    "stt_type": "azure-stt"
  },
  "2": {
    "model": "gpt-3.5-turbo",
    "start_text": "你好，俺是东北兔，请问有什么俺可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“东北兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-liaoning-XiaobeiNeural",
    "language": "zh-CN",
    "stt_type": "azure-stt"
  },
  "3": {
    "model": "gpt-3.5-turbo",
    "start_text": "Hi, I'm Fofo. Nice to meet you.",
    "prompt": "Your name is \"Fofo\". Your task is to chat with me. Please respond in English, keeping your answers brief – no more than 50 words each time!",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "en-US-AnaNeural",
    "language": "en",
    "stt_type": "azure-stt"
  },
  "4": {
    "model": "gpt-3.5-turbo",
    "start_text": "你好，额是夸夸兔，请问有什么额可以帮助你的吗？ ",
    "prompt": "夸夸我",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-shaanxi-XiaoniNeural",
    "language": "zh-CN",
    "stt_type": "azure-stt"
  },
  "5": {
    "model": "gpt-3.5-turbo",
    "start_text": "你好，我是山东兔，请问有什么我可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“山东兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-XiaoyiNeural",
    "language": "zh-CN",
    "stt_type": "azure-stt"
  },
  "6": {
    "model": "gpt-3.5-turbo",
    "start_text": "你好，我是台湾兔，请问有什么我可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“台湾兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-TW-HsiaoChenNeural",
    "language": "zh-CN",
    "stt_type": "azure-stt"
  },
  "7": {
    "model": "gpt-3.5-turbo",
    "start_text": "你好，我是红小兔，请问有什么我可以帮助你的吗？",
    "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“红小兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
    "max_message_count": 20,
    "temperature": 0.7,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "voice_name": "zh-CN-YunxiNeural",
    "language": "zh-CN",
    "stt_type": "azure-stt"
  }
}
```

docker-compose.yml
```yml
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /roles.json

      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt]
      STT_TYPE: azure-stt

      # OpenAI Whisper
      #OPENAI_WHISPER_API_BASE: https://api.chatanywhere.cn/v1
      OPENAI_WHISPER_KEY: sk-Jy***************pkXixDSiEuyFc3
      OPENAI_WHISPER_MODEL: whisper-1
      
      # Azure Whisper
      #AZURE_WHISPER_API_BASE: https://****.openai.azure.com
      AZURE_WHISPER_KEY: *********
      AZURE_WHISPER_DEPLOYMENT_NAME: wsp
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Default LLM(Large Language Model) type
      # Options: [openai, azure-openai]
      LLM_TYPE: azure-openai

      # OpenAI
      #OPENAI_OPENAI_API_BASE: https://api.chatanywhere.cn/v1
      OPENAI_OPENAI_KEY: sk-JyCcy6OXA4Z*************spkXixDSiEuyFc3

      #Azure OpenAI
      AZURE_OPENAI_KEY: 6413ad*******18c8f0daa8b
      AZURE_OPENAI_ENDPOINT: https://***.openai.azure.com/
      AZURE_OPENAI_VERSION: "2023-05-15"

      #Baidu YIYAN API
      #LLM_TYPE: yiyan
      YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [edge-tts, azure-tts, elevenlabs]
      # edge-tts is Free but slow
      TTS_TYPE: azure-tts

      # Azure TTS
      AZURE_TTS_KEY: d14389***************337ce
      AZURE_TTS_SERVICE_REGION: japaneast

      # elevenlabs
      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      AUDIO_DOWNLOAD_URL: http://1********:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy_server
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 1*********
      SPEECH_UDP_SERVER_PORT: 8085
```
