### ISSUE TITLE
只有toy一个客户端接入，发送语音无响应，audio目录下无内容

### ISSUE THREAD

**Issue by volans** [FoloToy/folotoy-server-self-hosting#68]
folotoy-nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
folotoy-nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
folotoy-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
folotoy-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
folotoy-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
folotoy-emqx-1   | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
folotoy-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
folotoy-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
folotoy-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: using the "epoll" event method
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: nginx/1.25.3
folotoy-emqx-1   | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-emqx-1   | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-emqx-1   | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-emqx-1   | EMQX_NODE__NAME [node.name]: emqx@172.18.0.2
folotoy-emqx-1   | 2023-11-14T22:25:14.486782+00:00 [warning] msg: still_waiting_for_emqx_app_to_be_ready, mfa: emqx_cluster_rpc:do_wait_for_emqx_ready/1(673)
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: OS: Linux 6.1.0-rpi4-rpi-v8
folotoy-emqx-1   | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-emqx-1   | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: start worker processes
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: start worker process 29
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: start worker process 30
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: start worker process 31
folotoy-emqx-1   | Listener ws:default on 0.0.0.0:8083 started.
folotoy-emqx-1   | Listener wss:default on 0.0.0.0:8084 started.
folotoy-nginx-1  | 2023/11/14 22:24:51 [notice] 1#1: start worker process 32
folotoy-emqx-1   | Listener http:dashboard on :18083 started.
folotoy-nginx-1  | 2023/11/14 22:34:05 [error] 30#30: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 192.168.50.66, server: localhost, request: "GET / HTTP/1.1", host: "192.168.50.249:8082"
folotoy-nginx-1  | 192.168.50.66 - - [14/Nov/2023:22:34:05 +0000] "GET / HTTP/1.1" 403 153 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" "-"
folotoy-nginx-1  | 2023/11/14 22:34:10 [error] 30#30: *1 open() "/usr/share/nginx/html/audio" failed (2: No such file or directory), client: 192.168.50.66, server: localhost, request: "GET /audio HTTP/1.1", host: "192.168.50.249:8082"
folotoy-nginx-1  | 192.168.50.66 - - [14/Nov/2023:22:34:10 +0000] "GET /audio HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" "-"
folotoy-emqx-1   | EMQX 5.3.1 is running now!

**Comment by lewangdev** [comment]
端口打开了没？参考下文档中的faq

**Comment by volans** [comment]
没有8085端口

```
 sudo ss -ltnp
State           Recv-Q           Send-Q                     Local Address:Port                      Peer Address:Port          Process                                           
LISTEN          0                4096                             0.0.0.0:18083                          0.0.0.0:*              users:(("docker-proxy",pid=26824,fd=4))          
LISTEN          0                4096                             0.0.0.0:1883                           0.0.0.0:*              users:(("docker-proxy",pid=26899,fd=4))          
LISTEN          0                4096                             0.0.0.0:8082                           0.0.0.0:*              users:(("docker-proxy",pid=26478,fd=4))          
LISTEN          0                4096                             0.0.0.0:8083                           0.0.0.0:*              users:(("docker-proxy",pid=26864,fd=4))          
LISTEN          0                128                              0.0.0.0:22                             0.0.0.0:*              users:(("sshd",pid=771,fd=3))                    
LISTEN          0                128                            127.0.0.1:631                            0.0.0.0:*              users:(("cupsd",pid=719,fd=7))                   
LISTEN          0                4096                                [::]:18083                             [::]:*              users:(("docker-proxy",pid=26830,fd=4))          
LISTEN          0                4096                                [::]:1883                              [::]:*              users:(("docker-proxy",pid=26910,fd=4))          
LISTEN          0                4096                                [::]:8082                              [::]:*              users:(("docker-proxy",pid=26486,fd=4))          
LISTEN          0                4096                                [::]:8083                              [::]:*              users:(("docker-proxy",pid=26871,fd=4))          
LISTEN          0                128                                 [::]:22                                [::]:*              users:(("sshd",pid=771,fd=4))                    
LISTEN          0                128                                [::1]:631                               [::]:*              users:(("cupsd",pid=719,fd=6)) 
```

我没有修改默认配置文件的端口设置，感觉是folotoy就没起来。

在EMQX的客户端列表里，没有folotoy

**Comment by volans** [comment]
`3920586b5c3d   lewangdev/folotoy-server:latest   "python3 folotoy/mai…"   3 hours ago   Restarting (0) 24 seconds ago                                                                                                                                                                                            folotoy-folotoy-1`

这个持续重启

**Comment by lewangdev** [comment]
发一下的 docker-compose.yml 和 roles.json 的配置

**Comment by volans** [comment]
```
/folotoy $ cat docker-compose.yml 
version: '3'

services:
 emqx:
   image: emqx/emqx:latest
   restart: always
   ports:
     - "1883:1883/tcp"
     - "18083:18083/tcp"
     - "8083:8083/tcp"
   volumes:
     - emqx-data:/opt/emqx/data
     - emqx-log:/opt/emqx/log
 nginx:
   image: nginx:latest
   restart: always
   ports:
     - "8082:80/tcp"
   volumes:
     - ./audio:/usr/share/nginx/html
 folotoy:
   image: lewangdev/folotoy-server:latest
   restart: always
   depends_on:
     emqx:
         condition: service_started
     nginx:
         condition: service_started
   ports:
     - "8085:8085/udp"
   volumes:
     - ./audio:/audio
     - ./roles.json:/roles.json
   environment:
     TZ: Pacific/Auckland

     LOG_LEVEL: DEBUG

     ROLES_FILE_PATH: /roles.json

     # Default STT(Sound To Text) type
     # Options: [openai-whisper, azure-whisper, azure-stt]
     STT_TYPE: openai-whisper

     # OpenAI Whisper
     #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.cc/v1
     OPENAI_WHISPER_KEY: sk-3idxxxxx
     OPENAI_WHISPER_MODEL: whisper-1
     
     # Azure Whisper
     AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
     AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
     AZURE_WHISPER_DEPLOYMENT_NAME: whisper
     AZURE_WHISPER_API_VERSION: 2023-09-01-preview

     # Azure STT
     AZURE_STT_KEY: a3cde7dxxxxx
     AZURE_STT_SERVICE_REGION: australiaeast 

     # Default LLM(Large Language Model) type
     # Options: [openai, azure-openai]
     LLM_TYPE: openai

     # OpenAI
     #OPENAI_OPENAI_API_BASE: https://one-api.xxx.cc/v1
     OPENAI_OPENAI_KEY: sk-3idRd5eDE9Op0Mxxxxxx


     #Azure OpenAI
     AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
     AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
     AZURE_OPENAI_API_VERSION: "2023-05-15"

     #Baidu YIYAN API
     #LLM_TYPE: yiyan
     YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
     YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx

     # If your elevenlabs is a free account, keep 2 here
     VOICE_EXECUTOR_MAX_WORKERS: 2

     # Default TTS(Text to Sound) type
     # Options: [edge-tts, azure-tts, elevenlabs, openai-tts]
     # edge-tts is Free but slow
     TTS_TYPE: edge-tts

     # Azure TTS
     AZURE_TTS_KEY: 7697178633xxxxx
     AZURE_TTS_SERVICE_REGION: australiaeast

     # elevenlabs
     ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
     ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

     # OpenAI TTS
     #OPENAI_TTS_API_BASE: https://one-api.xxx.cc/v1
     OPENAI_TTS_KEY: sk-16XnP3HLHWho21oO2m0AAAAAAAAAAAAAAAAAAAAAA
     OPENAI_TTS_MODEL: tts-1  

     AUDIO_DOWNLOAD_URL: http://192.168.50.249:8082
     AUDIO_SAVE_PATH: /audio

     # MQTT Broker
     MQTT_BROKER_HOST: emqx
     MQTT_BROKER_PORT: 1883
     MQTT_CLIENT_ID: folotoy
     MQTT_USERNAME: folotoy
     MQTT_PASSWORD: folotoy

     SPEECH_UDP_SERVER_HOST: 192.168.50.249
     SPEECH_UDP_SERVER_PORT: 8085

volumes:
 emqx-data:
 emqx-log:
```
