### ISSUE TITLE
本地部署了faster-whisper，docker-compose.yml 和roles.json 该如何配置

### ISSUE THREAD

**Issue by andrewChang** [FoloToy/folotoy-server-self-hosting#83]
尝试修改 docker-compose.yml

      # OpenAI Whisper
      # OPENAI_WHISPER_API_BASE: https://openai-api.magickchat.com/v1
      OPENAI_WHISPER_API_BASE: http://127.0.0.1:6006/v1

日志表明还是去调openai的接口了，查看https://docs.folotoy.com/docs/configuration/roles_config，没有本地化部署接口的介绍，请一并解答下ASR TTS和LLM本地化部署后，该如何配置？感谢
----------------------------------------------------
参照 https://github.com/lewangdev/faster-whisper
启动的服务地址：http://127.0.0.1:6006/v1/audio/transcriptions

**Comment by lewangdev** [comment]
如果在docker容器里面的访问 127.0.0.1，那要求服务要部署在同一个示例里面，如果是 STT(ASR)/LLM/TTS 是不同的实例，请使用自己的 server ip/server local ip 或者容器名来访问，注意这是 docker 的知识。

使用 docker-compose.yml 配置：
```yml
# STT(ASR)
OPENAI_WHISPER_API_BASE: http://<your_server_ip>:6006/v1

# LLM
OPENAI_OPENAI_API_BASE: http://<your_server_ip>:<your_port>/v1

# TTS
OPENAI_TTS_API_BASE: http://<your_server_ip>:<your_port>/v1
```

也可以修改 roles.json，例如修改第6个角色：

```json
...
  "6": {
    "model": "gpt-turbo-3.5",
    "system_prompt": "你是大模型",
    "start_text": "你好，我是唐伯兔，请问有什么我可以帮助你的吗？",
    "prompt": "你熟读中国所有古典书籍,非常有才华,而擅长讲中国古典寓言故事",
    "max_message_count": 5,
    "temperature": 0.7,
    "max_tokens": 200,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "llm_config": {
        "api_base": "http://192.168.52.45:8000/v1"
    },
    "stt_type": "openai-whisper",
    "stt_config": {
            "api_base": "http://192.168.52.45:8801/v1"
    },
    "tts_type":"openai-tts",
    "tts_config": {
        "api_base": "http://192.168.52.45:8501/v1",
        "voice_name": "92"
    }
  },
...
  
```
